//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelImage
    {
        public long Id { get; set; }
        public Nullable<long> PersonelID { get; set; }
        public string PersonelImage1 { get; set; }
    
        public virtual Personel Personel { get; set; }
        public object ImageFile { get; internal set; }
    }
}
