//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.EntitiyFramework
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.PersonelImage = new HashSet<PersonelImage>();
        }
    
        public long Id { get; set; }
        public Nullable<long> DepartmanId { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public Nullable<decimal> Wage { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> Gender { get; set; }
        public bool Married { get; set; }
    
        public virtual Departman Departman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonelImage> PersonelImage { get; set; }
        public HttpPostedFileBase FileName { get; internal set; }
        public string PersonelImage1 { get; internal set; }
    }
}
